version: '3.7'

services:
    #######################################
    # Delivery Service
    #######################################
    delivery-service:
        container_name: delivery-service
        env_file: "env/${ENV}.env"
        build:
            context: "."
        image: delivery-service
        networks:
        - quick-service-net
        ports:
        - "4099:8000"
        volumes:
            - .:/usr/src/app
            - ./media:/usr/src/app/media
#            - ./node_modules:/usr/src/app/node_modules
        restart: unless-stopped

networks:
  quick-service-net:
      name: quick-service-network
      ipam:
          driver: default
          config:
              - subnet: "192.168.0.0/24"
              - subnet: "4001:5984:5989::/64"
