version: "3.7"
services:
  #######################################
  # Database Service
  #######################################
  db_quick_service:
    container_name: "db_quick_service"
    build:
        context: ./database
    env_file: "database/env/${ENV}.env"
    ports:
      - 4088:5432  
    networks:
        - quick-service-net
    volumes:
    - "db_volume:/var/lib/postgresql/data"

networks:
  quick-service-net:
      name: quick-service-network
      ipam:
          driver: default
          config:
              - subnet: "192.168.0.0/24"
              - subnet: "4001:5984:5989::/64"



volumes:
  db_volume:
