version: '3.7'

services:
    #######################################
    # Redis Service
    #######################################
    minio-service:
        image: minio/minio
        container_name: minio-service
        hostname: minio-service
        restart: unless-stopped
        volumes:
          - ./media:/data
        ports:
          - "9001:9000"
        networks:
         - quick-service-net
        env_file: "env/${ENV}.env"
        command:  server /data
        healthcheck:
          test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
          interval: 30s
          timeout: 20s
          retries: 3

networks:
  quick-service-net:
      name: quick-service-network
      ipam:
          driver: default
          config:
              - subnet: "192.168.0.0/24"
              - subnet: "4001:5984:5989::/64"